### ISSUE TITLE
If `fn` is an asynchronous function, this `try catch` will be useless ？

### ISSUE THREAD

**Issue by liujiede** [koajs/compose#101]
![image](https://user-images.githubusercontent.com/5275769/60246336-12b67b00-98f1-11e9-9d42-ccf6b7632b01.png)

**Comment by fl0w** [comment]
before the function returns a promise, it can throw "synchronous" (in context). This simply catches errors thrown before the promise is returned.

**Comment by jonathanong** [comment]
people might mistakingly return a regular function
