### ISSUE TITLE
Behavior changes on 4.2.0

### ISSUE THREAD

**Issue by legendecas** [koajs/compose#106]
PR https://github.com/koajs/compose/pull/96 introduced an operation `reduce` on each call of `compose`, which shallow copies the middleware array. Previously middlewares can be added after `koa.listen`, with the PR landed middlewares added by `koa.use` after `koa.listen` are no longer working. Furthermore, `koa.middleware` property no longer reflects the correct middleware array since `compose` fn holds its own copy of it.

Should this be considered as breaking changes/bugs?

**Comment by dead-horse** [comment]
@legendecas I've set koa-compose@4.1.0 to the latest tag.

**Comment by dead-horse** [comment]
We can fix this in koa-compose, but I don't think it is really needed to add this feature https://github.com/koajs/compose/pull/96

**Comment by legendecas** [comment]
One point as mentioned above is that koa.middleware property no longer reflects the correct middleware array since compose fn holds its own copy of it. I'd believe this feature better goes into `koa` package so that `koa.middleware` can reflect the correct middleware array.

**Comment by dead-horse** [comment]
Personally I'd like to revert this feature which I think It's not a required feature, and makes compose use too varied.

**Comment by niftylettuce** [comment]
I published a deprecation notice for v4.2.0
