### ISSUE TITLE
Add debug logs before and after each middleware executes

### ISSUE THREAD

**Issue by imaustink** [koajs/compose#108]
It would be extremely useful for debugging purposes if `koa-compose` logged the name of each middleware before and after it executed.

I propose adding the `debug` packaging and configuration a namespace of `koa:compose` to [match `Koa`'s convention](https://github.com/koajs/koa/blob/master/lib/application.js#L9) and using it implement the aforementioned logs.

**Comment by jonathanong** [comment]
you don't want to just add debug logs. the real solution is https://github.com/koajs/compose/issues/6
