### ISSUE TITLE
Unexpected identifier - `of`

### ISSUE THREAD

**Issue by vjpr** [koajs/compose#39]
This makes Node v4 a requirement which is not mentioned anywhere.

Shame to break Node 0.12.x support for such a minor syntax change, seeing as Koa@2 supports 0.12.x.

**Comment by coderhaoxin** [comment]
koa@2 requires node@4+

**Comment by blakeembrey** [comment]
@coderhaoxin Would you consider making the changes to just `koa-compose`? It'd be a bummer to duplicate all the code when it'd be nice just to re-use this library for arbitrary (non-Koa specific) async middleware.

**Comment by coderhaoxin** [comment]
> Would you consider making the changes to just koa-compose?

@blakeembrey I don't know what you meant. :cry:

**Comment by blakeembrey** [comment]
This module is `koa-compose`, not `koa`. So would you consider making the code here ES5 instead of ES6 so that node <= 0.12 can use it? I'd like to use the module without replicating it for my own uses.

**Comment by coderhaoxin** [comment]
@jonathanong we need change `for of` to normal `for loop`! 

Should we add node <= 0.12 to the travis ?

**Comment by blakeembrey** [comment]
Thanks! The only other piece is the `const`. I'd love if you could test down to 0.10 too.

**Comment by blakeembrey** [comment]
For reference, I want to use it for a HTTP request library (https://github.com/blakeembrey/popsicle/pull/49) and have written a corresponding type definition (https://github.com/typed-typings/npm-koa-compose/blob/master/index.d.ts) in case you're interested in supporting TypeScript users in the module.
