### ISSUE TITLE
swap tags + branches - v2 / v3

### ISSUE THREAD

**Issue by tejasmanohar** [koajs/compose#40]
koa-compose@3 should have `dist-tag` of `next` on npm and @2 `latest` since v3 is for koa v2 which is currently in alpha on npm

**Comment by coderhaoxin** [comment]
https://github.com/koajs/compose/issues/35 +1

**Comment by jonathanong** [comment]
:+1: adding both of you as npm owners

**Comment by tejasmanohar** [comment]
thx, changed.

```
$ npm dist-tag ls koa-compose
latest: 2.3.0
next: 3.0.0
```

**Comment by tejasmanohar** [comment]
@jonathanong mind moving `v2.x` code to master and `master` code to `next` so it lines up with all the rest of the repos in this org? more intuitive for `latest` to be on `master`. i can do it too if you add me to repo.

ps: looks like bf5eb1d946b4395f16413606dded11813bf7888d (maybe it was a PR?) up'd the version... guessing no one noticed because 2.3.1 hasn't been published to npm.

**Comment by jonathanong** [comment]
added to the team :)

**Comment by tejasmanohar** [comment]
@jonathanong is it possible I only have read access and not write? when I try to edit a file on github interface...
>You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork tejasmanohar/compose, so you can send a pull request.

when I try to push to `origin`-
```
$ git remote -v
origin	git@github.com:koajs/compose.git (fetch)
origin	git@github.com:koajs/compose.git (push)

$ git push origin next
ERROR: Permission to koajs/compose.git denied to tejasmanohar.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

iirc, "read" is a permission level even for public repos- github orgs are a bit wonky :P

**Comment by jonathanong** [comment]
oh shit

**Comment by jonathanong** [comment]
i kind of wish `write` was default. it's `read` by default :(

**Comment by tejasmanohar** [comment]
@jonathanong thx. you should be able to change that [here](https://github.com/organizations/koajs/settings/member_privileges)

**Comment by tejasmanohar** [comment]
done

**Comment by jonathanong** [comment]
oh shit sweet
