### ISSUE TITLE
Is 2.5.0 a breaking change?

### ISSUE THREAD

**Issue by Ramshackle-Jamathon** [koajs/compose#66]

**Comment by PlasmaPower** [comment]
[I don't see why it would be](https://github.com/koajs/compose/compare/eca096b...master). What makes you think so?

**Comment by mikeybtn** [comment]
I think it is (though arguably in the realm of undocumented behavior; it bit us, at least). See #67.

**Comment by jonathanong** [comment]
merging with https://github.com/koajs/compose/issues/67
