### ISSUE TITLE
Reorganize tests, and switch to Jest

### ISSUE THREAD

**Issue by PlasmaPower** [koajs/compose#76]
Right now all of the tests are under one `describe`. I'm not sure we need to split them into more files, but multiple `describe` sections would certainly be nice.

**Comment by JeffRMoore** [comment]
How do folks feel about converting to jest?

**Comment by PlasmaPower** [comment]
Sounds good, we should probably wrap that into the PR for reorganizing tests. I'll change the issue to include both.

**Comment by JeffRMoore** [comment]
I have a version of the test suite in jest with 100% coverage that I've been using for experimentation.  (Love watch).  Its based on the skip-next branch and I added flow support and semi-colons with prettier.  I need to clean it  up and reformat it back.  I'm prepping an update to skip-next.  I'll work on submitting the suite back after that.  This is the organization I used:
```
  compose
    ✓ should throw if middleware doesn not return a promise
    ✓ should keep the context across multiple middleware (1ms)
    ✓ should reject on errors in middleware (2ms)
    ✓ should not call next with middleware parameters
    ✓ should not call skipNext with middleware parameters (1ms)
    ✓ should throw if skipNext() is called multiple times at the beginning
    ✓ should throw if next() is called multiple times at the beginning (1ms)
    ✓ should throw if skipNext() is called multiple times at the end
    ✓ should throw if next() is called multiple times at the end
    ✓ should throw if skipNext() is called after next() (1ms)
    ✓ should throw if next() is called after skipNext()
    empty stack
      ✓ should propagate the return value of calling next (2ms)
      ✓ should catch an exception in next (1ms)
      ✓ should catch a rejected promise in next (1ms)
      ✓ should only accept functions for next
      ✓ should only accept functions for skipNext
    parameters
      ✓ should only accept an array of middleware
      ✓ should only accept middleware as functions (1ms)
    deep stack
      ✓ should call middleware stack in the right order (1ms)
      ✓ should be able to be called twice (1ms)
      ✓ should propagate the value of calling next
      with Skip at the end
        ✓ should propagate the value of calling skipNext
        ✓ should catch an exception in skipNext (1ms)
        ✓ should catch a rejected promise in skipNext
```
I haven't worked on any sort of build integration for coverage or failures.

**Comment by PlasmaPower** [comment]
Looks good! Reliant on skipNext though, and nothing against it but I don't think it'll get merged (presumably breaking change after koa@2 finalized).

**Comment by jonathanong** [comment]
oh wow i did this https://github.com/koajs/compose/pull/90

removing the top-level describe isn't worth the git diff imo, i'd rather just put all new tests in a new file
