### ISSUE TITLE
Unit test to verify if it handles wrapped non-async functions is wrong.

### ISSUE THREAD

**Issue by lewisdiamond** [koajs/compose#92]
see: https://github.com/koajs/compose/blob/e754ca3c13e9248b3f453d98ea0b618e09578e2d/test/test.js#L234

the `then` function throws `new Error` which is the same type as the `stack` function. The returned promise's `then` function should fail the test rather than throw a `new Error`.

**Comment by jonathanong** [comment]
thanks!
