### ISSUE TITLE
Multiple next with non async function

### ISSUE THREAD

**Issue by xyluet** [koajs/compose#99]
Hi, 

I wrote test like below, it throw an error but it come like this 

`UnhandledPromiseRejectionWarning: Error: next() called multiple times`

and the test failed. Is this expected?

```js
  it(`should throw if next() is called multiple times in non async function`, async () => {
    const stack = [];

    stack.push((ctx, next) => {
      next();
      next();
    });

    expect.hasAssertions();

    try {
      await compose(stack)({});
    } catch (error) {
      expect(error).toBeInstanceOf(Error);
    }
  });
```

**Comment by Runrioter** [comment]
```
 stack.push((ctx, next) => {
      next();
      next();
    });
```

Here, two called `next()`. It is wrong.

**Comment by xyluet** [comment]
Yes, so it should caught in try catch, but it didn't.

**Comment by Runrioter** [comment]
Try this `await expect(compose(stack)({})).rejects.toThrowError('next() called multiple times');` ?

@xyluet

**Comment by xyluet** [comment]
```js
it(`should throw if next() is called multiple times in non async function`, async () => {
    const stack = [];

    stack.push((ctx, next) => {
      next();
      next();
    });

    await expect(compose(stack)({})).rejects.toThrowError('next() called multiple times');
  });
```


I tried that before, but it resolved to value

```
expect(received).rejects.toThrowError()

    Expected received Promise to reject, instead it resolved to value
      undefined
```

**Comment by fl0w** [comment]
expect doesn't return a promise, so the last example wouldn't work.
compose doesn't support sync calls, and so your last `next()` occurs out of context and the throw isn't caught.

**Comment by Runrioter** [comment]
No, koa-compose support sync calls. The problem here is `next()` return a Promise. We need return Promise or include it in async function (had been included in test case). 

The following one is use promise-based sync function.

```javascript
  it(`should throw if next() is called multiple times in non async function`, () => {
    const stack = [];

    stack.push((ctx, next) => {
      return next().then(() => {
        return next()
      });
    });

    return compose(stack)({}).then(() => {
      throw new Error('boom')
    }, (err) => {
      assert(/multiple times/.test(err.message))
    })
  });
```

**Comment by fl0w** [comment]
@Runrioter that's exactly what I ment (I maybe expressed it badly). If you're dealing with them as promises the request chain isn't synchronous, the execute on a new tick.
